### ISSUE TITLE
 'ReadyRole' in '360' seconds.

### ISSUE THREAD

**Issue by pollosp** [MSOpenTech/vagrant-azure#26]
Hello again,
If the provider takes more than 5 minutes to create the instance in Azure, it returns this "error":
==> default: Machine failed to reached state 'ReadyRole' in '360' seconds

and the bootstrap script fails.

In US zone deploy VM is taking arround 8 to 10 minutes.
In the doc is not any var to incrase this timeout, can you include it if it doesn´t exists?

Thanks again.

**Comment by devigned** [comment]
This can be fixed by specifying the boot timeout via config.vm.boot_timeout = 1000 or some other arbitrarily large number of seconds. There is now an example in the readme. #44 changed eliminated the config value from being set, thus allowing the user to specify the boot_timeout in the vagrant file.
